name: Generate Migration File

env:
  MYSQL_DATABASE: test_db
  MYSQL_USER: user01
  MYSQL_PASSWORD: password
  MYSQL_HOST: localhost
  BACKEND_PATH: backend
  ALEMBIC_PATH: backend/db

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write

jobs:
  generate-migrations:
    runs-on: ubuntu-latest
    
    # services:
    #   mysql:
    #     image: mysql:8.0
    #     env:
    #       MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
    #       MYSQL_USER: ${{ env.MYSQL_USER }}
    #       MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
    #       MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
          echo '6' ${{ github.event.pull_request.base.sha }}
          echo '7' ${{ github.event.pull_request.head.sha }}

      # - name: Fetch Base Branch Latest Commit
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.head_ref }}	
      #     fetch-depth: 1

      # - name: Fetch Base Branch Latest Commit
      #   uses: actions/checkout@v4

      # - name: Notice diff files
      #   id: skip-test
      #   run: |
      #     MERGE_BASE_SHA=$(git rev-list -1 $GITHUB_REF)
      #     echo "MERGE_BASE_SHA $MERGE_BASE_SHA"
      #     echo "GITHUB_SHA: $GITHUB_SHA"
      #     CHANGE_FILES=$(git diff --name-only $MERGE_BASE_SHA $GITHUB_SHA)
      #     echo "Changed files: $CHANGED_FILES"

      # - name: Install poetry
      #   run: pipx install poetry

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: '${{ env.BACKEND_PATH }}/.python-version'
      #     cache: 'poetry'

      # - name: Install dependencies
      #   working-directory: ${{ env.BACKEND_PATH }}
      #   run: |
      #     poetry env use $(cat .python-version)
      #     poetry install --no-interaction

      # - name: Upgrade database to the current version
      #   working-directory: ${{ env.ALEMBIC_PATH }}
      #   run: |
      #     poetry run alembic upgrade head

      # - name: Generate migration file
      #   working-directory: ${{ env.ALEMBIC_PATH }}
      #   run: |
      #     poetry run alembic revision --autogenerate -m "Auto-generated migration by github action at ($(date +%Y%m%d%H%M%S))"

      # - name: commit and push migration file on success
      #   working-directory: ${{ env.ALEMBIC_PATH }}
      #   if: success()
      #   run: |
      #     git config --global user.email "action@github.com"
      #     git config --global user.name "GitHub Action"
      #     git add migrations/versions/*.py
      #     git commit -m "Auto-generated migration by github action at ($(date +%Y%m%d%H%M%S)) from ci"
      #     git push
